### ISSUE TITLE
Basic Chat

### ISSUE THREAD

**Issue by zakarhino** [forinlanguages/forinlanguages#8]
Only need to be one way, from creator to people connected.

**Comment by ydjjabt** [comment]
what exactly u mean creator? i assume u mean the peer that initiate the connection with the other peer?

**Comment by zakarhino** [comment]
Completed.

@ydjjabt I meant for the MVP we only need to have one-way communication from the Sender to the client because building a network style peer system is a nice to have due to its difficulty.
